# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\программы\1000ListNik\instagramm\design\3_2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(614, 1024)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 611, 1011))
        self.widget.setObjectName("widget")
        self.change_text = QtWidgets.QLabel(self.widget)
        self.change_text.setGeometry(QtCore.QRect(10, -60, 601, 231))
        self.change_text.setObjectName("change_text")
        self.find_all = QtWidgets.QGroupBox(self.widget)
        self.find_all.setGeometry(QtCore.QRect(40, 100, 121, 81))
        self.find_all.setTitle("")
        self.find_all.setObjectName("find_all")
        self.rectangle = QtWidgets.QGroupBox(self.find_all)
        self.rectangle.setGeometry(QtCore.QRect(10, 10, 101, 61))
        self.rectangle.setTitle("")
        self.rectangle.setObjectName("rectangle")
        self.label = QtWidgets.QLabel(self.rectangle)
        self.label.setGeometry(QtCore.QRect(20, 10, 61, 41))
        self.label.setObjectName("label")
        self.find_all_3 = QtWidgets.QGroupBox(self.widget)
        self.find_all_3.setGeometry(QtCore.QRect(170, 100, 131, 81))
        self.find_all_3.setTitle("")
        self.find_all_3.setObjectName("find_all_3")
        self.rectangle_4 = QtWidgets.QGroupBox(self.find_all_3)
        self.rectangle_4.setGeometry(QtCore.QRect(10, 10, 111, 61))
        self.rectangle_4.setTitle("")
        self.rectangle_4.setObjectName("rectangle_4")
        self.found_like = QtWidgets.QLabel(self.rectangle_4)
        self.found_like.setGeometry(QtCore.QRect(20, 10, 81, 41))
        self.found_like.setObjectName("found_like")
        self.big_rect = QtWidgets.QGroupBox(self.widget)
        self.big_rect.setGeometry(QtCore.QRect(10, 270, 561, 361))
        self.big_rect.setTitle("")
        self.big_rect.setObjectName("big_rect")
        self.tasks = QtWidgets.QGroupBox(self.big_rect)
        self.tasks.setGeometry(QtCore.QRect(10, 20, 531, 101))
        self.tasks.setTitle("")
        self.tasks.setObjectName("tasks")
        self.insta_img1 = QtWidgets.QGroupBox(self.tasks)
        self.insta_img1.setGeometry(QtCore.QRect(10, 10, 81, 81))
        self.insta_img1.setTitle("")
        self.insta_img1.setObjectName("insta_img1")
        self.inst_login = QtWidgets.QLabel(self.tasks)
        self.inst_login.setGeometry(QtCore.QRect(100, 10, 221, 61))
        self.inst_login.setObjectName("inst_login")
        self.heart = QtWidgets.QGroupBox(self.tasks)
        self.heart.setGeometry(QtCore.QRect(320, 10, 81, 81))
        self.heart.setTitle("")
        self.heart.setObjectName("heart")
        self.prise = QtWidgets.QLabel(self.tasks)
        self.prise.setGeometry(QtCore.QRect(340, 20, 181, 61))
        self.prise.setObjectName("prise")
        self.task2 = QtWidgets.QGroupBox(self.big_rect)
        self.task2.setGeometry(QtCore.QRect(10, 130, 531, 101))
        self.task2.setTitle("")
        self.task2.setObjectName("task2")
        self.insta_img2 = QtWidgets.QGroupBox(self.task2)
        self.insta_img2.setGeometry(QtCore.QRect(10, 10, 81, 81))
        self.insta_img2.setTitle("")
        self.insta_img2.setObjectName("insta_img2")
        self.inst_login2 = QtWidgets.QLabel(self.task2)
        self.inst_login2.setGeometry(QtCore.QRect(100, 10, 211, 61))
        self.inst_login2.setObjectName("inst_login2")
        self.heart2 = QtWidgets.QGroupBox(self.task2)
        self.heart2.setGeometry(QtCore.QRect(320, 10, 81, 81))
        self.heart2.setTitle("")
        self.heart2.setObjectName("heart2")
        self.prise2 = QtWidgets.QLabel(self.task2)
        self.prise2.setGeometry(QtCore.QRect(340, 20, 181, 61))
        self.prise2.setObjectName("prise2")
        self.task3 = QtWidgets.QGroupBox(self.big_rect)
        self.task3.setGeometry(QtCore.QRect(10, 240, 531, 101))
        self.task3.setTitle("")
        self.task3.setObjectName("task3")
        self.insta_img3 = QtWidgets.QGroupBox(self.task3)
        self.insta_img3.setGeometry(QtCore.QRect(10, 10, 81, 81))
        self.insta_img3.setTitle("")
        self.insta_img3.setObjectName("insta_img3")
        self.inst_login3 = QtWidgets.QLabel(self.task3)
        self.inst_login3.setGeometry(QtCore.QRect(100, 0, 211, 61))
        self.inst_login3.setObjectName("inst_login3")
        self.heart3 = QtWidgets.QGroupBox(self.task3)
        self.heart3.setGeometry(QtCore.QRect(320, 10, 81, 81))
        self.heart3.setTitle("")
        self.heart3.setObjectName("heart3")
        self.prise3 = QtWidgets.QLabel(self.task3)
        self.prise3.setGeometry(QtCore.QRect(340, 20, 171, 61))
        self.prise3.setObjectName("prise3")
        self.button_task1 = QtWidgets.QPushButton(self.widget)
        self.button_task1.setGeometry(QtCore.QRect(24, 290, 541, 101))
        self.button_task1.setStyleSheet("background: rgba(0,0,0,0);")
        self.button_task1.setText("")
        self.button_task1.setObjectName("button_task1")
        self.button_task3 = QtWidgets.QPushButton(self.widget)
        self.button_task3.setGeometry(QtCore.QRect(20, 510, 541, 101))
        self.button_task3.setStyleSheet("background: rgba(0,0,0,0);")
        self.button_task3.setText("")
        self.button_task3.setObjectName("button_task3")
        self.button_task2 = QtWidgets.QPushButton(self.widget)
        self.button_task2.setGeometry(QtCore.QRect(30, 400, 531, 101))
        self.button_task2.setStyleSheet("background: rgba(0,0,0,0);")
        self.button_task2.setText("")
        self.button_task2.setObjectName("button_task2")
        self.ended_session = QtWidgets.QGroupBox(self.widget)
        self.ended_session.setGeometry(QtCore.QRect(10, 640, 261, 80))
        self.ended_session.setTitle("")
        self.ended_session.setObjectName("ended_session")
        self.button_session = QtWidgets.QPushButton(self.widget)
        self.button_session.setGeometry(QtCore.QRect(10, 640, 261, 81))
        self.button_session.setStyleSheet("background: rgba(0,0,0,0);")
        self.button_session.setText("")
        self.button_session.setObjectName("button_session")
        self.coin_text = QtWidgets.QLabel(self.widget)
        self.coin_text.setGeometry(QtCore.QRect(320, 190, 291, 61))
        self.coin_text.setObjectName("coin_text")
        self.ended_session_text = QtWidgets.QLabel(self.widget)
        self.ended_session_text.setGeometry(QtCore.QRect(30, 640, 241, 71))
        self.ended_session_text.setObjectName("ended_session_text")
        self.give_coins_button = QtWidgets.QPushButton(self.widget)
        self.give_coins_button.setGeometry(QtCore.QRect(290, 640, 281, 81))
        self.give_coins_button.setStyleSheet("background: rgba(0,0,0,0);")
        self.give_coins_button.setText("")
        self.give_coins_button.setObjectName("give_coins_button")
        self.ended_session_2 = QtWidgets.QGroupBox(self.widget)
        self.ended_session_2.setGeometry(QtCore.QRect(290, 640, 281, 80))
        self.ended_session_2.setTitle("")
        self.ended_session_2.setObjectName("ended_session_2")
        self.ended_session_text_2 = QtWidgets.QLabel(self.widget)
        self.ended_session_text_2.setGeometry(QtCore.QRect(360, 640, 211, 71))
        self.ended_session_text_2.setObjectName("ended_session_text_2")
        self.change_text.raise_()
        self.find_all.raise_()
        self.find_all_3.raise_()
        self.big_rect.raise_()
        self.button_task1.raise_()
        self.button_task3.raise_()
        self.button_task2.raise_()
        self.ended_session.raise_()
        self.coin_text.raise_()
        self.ended_session_text.raise_()
        self.ended_session_2.raise_()
        self.ended_session_text_2.raise_()
        self.give_coins_button.raise_()
        self.button_session.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 614, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.change_text.setText(_translate("MainWindow", "Выбери задание"))
        self.label.setText(_translate("MainWindow", "Всё"))
        self.found_like.setText(_translate("MainWindow", "Лайк"))
        self.inst_login.setText(_translate("MainWindow", "wooman"))
        self.prise.setText(_translate("MainWindow", "1 руб."))
        self.inst_login2.setText(_translate("MainWindow", "wooman"))
        self.prise2.setText(_translate("MainWindow", "1 руб."))
        self.inst_login3.setText(_translate("MainWindow", "wooman"))
        self.prise3.setText(_translate("MainWindow", "1 руб."))
        self.coin_text.setText(_translate("MainWindow", "0 руб."))
        self.ended_session_text.setText(_translate("MainWindow", "Закончить"))
        self.ended_session_text_2.setText(_translate("MainWindow", "Выдать"))

